/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BOMItem {
  'id' : string,
  'unit' : string,
  'workOrderId' : string,
  'quantity' : bigint,
  'materialName' : string,
  'companyId' : CompanyId,
}
export interface CommunicationLog {
  'id' : string,
  'date' : string,
  'note' : string,
  'logType' : string,
  'customerId' : string,
  'companyId' : CompanyId,
}
export interface Company {
  'id' : CompanyId,
  'employeeCount' : bigint,
  'managers' : Array<Principal>,
  'owner' : Principal,
  'name' : string,
  'sector' : string,
  'email' : string,
  'foundingYear' : bigint,
  'taxNumber' : string,
  'address' : string,
  'authorizedPerson' : string,
  'phone' : PhoneNumber,
}
export type CompanyId = string;
export interface CompanyMembership {
  'roleCode' : bigint,
  'grantedModules' : Array<string>,
  'companyId' : string,
}
export interface CompanyProfile {
  'employeeCount' : bigint,
  'name' : string,
  'sector' : string,
  'email' : string,
  'foundingYear' : bigint,
  'taxNumber' : string,
  'address' : string,
  'authorizedPerson' : string,
  'phone' : PhoneNumber,
}
export interface Customer {
  'id' : string,
  'contactInfo' : string,
  'customerCompanyName' : string,
  'name' : string,
  'companyId' : CompanyId,
}
export interface DashboardSummary {
  'totalEmployees' : bigint,
  'openProjects' : bigint,
  'pendingInvoices' : bigint,
  'totalStaff' : bigint,
  'lowStockProducts' : bigint,
  'totalCustomers' : bigint,
}
export type EmployeeCode = string;
export interface EmployeeRecord {
  'id' : string,
  'title' : string,
  'principal' : [] | [Principal],
  'hireDate' : string,
  'name' : string,
  'department' : string,
  'companyId' : CompanyId,
}
export interface FinancialSummary {
  'invoiceCount' : bigint,
  'totalIncome' : bigint,
  'totalExpenses' : bigint,
  'paidInvoiceCount' : bigint,
  'netBalance' : bigint,
}
export interface Invoice {
  'id' : string,
  'status' : string,
  'lineItems' : Array<InvoiceLineItem>,
  'client' : string,
  'total' : bigint,
  'date' : string,
  'companyId' : CompanyId,
}
export interface InvoiceLineItem {
  'description' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface LeaveRequest {
  'id' : string,
  'status' : string,
  'endDate' : string,
  'employeeId' : string,
  'leaveType' : string,
  'startDate' : string,
  'companyId' : CompanyId,
}
export interface PhoneNumber { 'countryCode' : string, 'number' : string }
export interface Product {
  'id' : string,
  'sku' : string,
  'name' : string,
  'quantityOnHand' : bigint,
  'category' : string,
  'unitPrice' : bigint,
  'companyId' : CompanyId,
}
export interface Project {
  'id' : string,
  'status' : string,
  'name' : string,
  'description' : string,
  'deadline' : string,
  'teamMembers' : Array<Principal>,
  'companyId' : CompanyId,
}
export interface ProjectTask {
  'id' : string,
  'status' : string,
  'assignee' : [] | [Principal],
  'title' : string,
  'dueDate' : string,
  'projectId' : string,
  'companyId' : CompanyId,
}
export interface PurchaseOrder {
  'id' : string,
  'status' : string,
  'orderDate' : string,
  'totalAmount' : bigint,
  'expectedDelivery' : string,
  'items' : string,
  'supplierId' : string,
  'companyId' : CompanyId,
}
export interface Role {
  'permissions' : Array<string>,
  'name' : string,
  'parentRole' : [] | [string],
}
export type RoleAssignmentResult = { 'alreadyAssigned' : null } |
  { 'invalidCode' : null } |
  { 'invalidRole' : null } |
  { 'success' : null } |
  { 'insufficientPermissions' : null };
export interface SalaryInfo {
  'id' : string,
  'employeeId' : string,
  'currency' : string,
  'baseSalary' : bigint,
  'companyId' : CompanyId,
}
export interface SalesOpportunity {
  'id' : string,
  'closeDate' : string,
  'stage' : string,
  'estimatedValue' : bigint,
  'customerId' : string,
  'companyId' : CompanyId,
}
export interface Staff {
  'roleCode' : bigint,
  'principal' : Principal,
  'employeeCode' : EmployeeCode,
  'grantedModules' : Array<string>,
  'name' : string,
  'projectManager' : string,
  'memberships' : Array<CompanyMembership>,
  'companyId' : CompanyId,
}
export interface StockMovement {
  'id' : string,
  'date' : string,
  'productId' : string,
  'movementType' : string,
  'quantity' : bigint,
  'reason' : string,
  'companyId' : CompanyId,
}
export interface Supplier {
  'id' : string,
  'contactInfo' : string,
  'name' : string,
  'category' : string,
  'rating' : bigint,
  'companyId' : CompanyId,
}
export interface Transaction {
  'id' : string,
  'transactionType' : string,
  'date' : string,
  'description' : string,
  'category' : string,
  'amount' : bigint,
  'companyId' : CompanyId,
}
export interface UserProfile {
  'roleCode' : bigint,
  'employeeCode' : string,
  'name' : string,
  'projectManager' : string,
  'memberships' : Array<CompanyMembership>,
  'companyId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkOrder {
  'id' : string,
  'status' : string,
  'endDate' : string,
  'productName' : string,
  'notes' : string,
  'quantity' : bigint,
  'startDate' : string,
  'companyId' : CompanyId,
}
export interface WorkflowTask {
  'id' : string,
  'status' : string,
  'assignee' : [] | [Principal],
  'title' : string,
  'tags' : Array<string>,
  'dueDate' : string,
  'description' : string,
  'priority' : string,
  'companyId' : CompanyId,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBOMItem' : ActorMethod<[CompanyId, BOMItem], BOMItem>,
  'addCommunicationLog' : ActorMethod<
    [CompanyId, CommunicationLog],
    CommunicationLog
  >,
  'addCustomRole' : ActorMethod<[string, Role], undefined>,
  /**
   * / ==========================
   * / CRM Module
   * / ==========================
   */
  'addCustomer' : ActorMethod<[CompanyId, Customer], Customer>,
  /**
   * / ==========================
   * / HR Module
   * / ==========================
   */
  'addEmployee' : ActorMethod<[CompanyId, EmployeeRecord], EmployeeRecord>,
  'addInvoice' : ActorMethod<[CompanyId, Invoice], Invoice>,
  'addLeaveRequest' : ActorMethod<[CompanyId, LeaveRequest], LeaveRequest>,
  /**
   * / ==========================
   * / Inventory Module
   * / ==========================
   */
  'addProduct' : ActorMethod<[CompanyId, Product], Product>,
  'addPurchaseOrder' : ActorMethod<[CompanyId, PurchaseOrder], PurchaseOrder>,
  'addSalaryInfo' : ActorMethod<[CompanyId, SalaryInfo], SalaryInfo>,
  'addSalesOpportunity' : ActorMethod<
    [CompanyId, SalesOpportunity],
    SalesOpportunity
  >,
  'addStaffToCompany' : ActorMethod<
    [CompanyId, EmployeeCode, string],
    RoleAssignmentResult
  >,
  'addStockMovement' : ActorMethod<[CompanyId, StockMovement], StockMovement>,
  /**
   * / ==========================
   * / Procurement Module
   * / ==========================
   */
  'addSupplier' : ActorMethod<[CompanyId, Supplier], Supplier>,
  /**
   * / ==========================
   * / Accounting Module
   * / ==========================
   */
  'addTransaction' : ActorMethod<[CompanyId, Transaction], Transaction>,
  /**
   * / ==========================
   * / Manufacturing Module
   * / ==========================
   */
  'addWorkOrder' : ActorMethod<[CompanyId, WorkOrder], WorkOrder>,
  /**
   * / ==========================
   * / Workflow Module
   * / ==========================
   */
  'addWorkflowTask' : ActorMethod<[CompanyId, WorkflowTask], WorkflowTask>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCompany' : ActorMethod<[CompanyProfile], Company>,
  /**
   * / ==========================
   * / Project Management Module
   * / ==========================
   */
  'createProject' : ActorMethod<[CompanyId, Project], Project>,
  'createProjectTask' : ActorMethod<[CompanyId, ProjectTask], ProjectTask>,
  'findByName' : ActorMethod<[string], [] | [Company]>,
  'findByOwner' : ActorMethod<[Principal], [] | [Company]>,
  'findByToken' : ActorMethod<[string], [] | [Company]>,
  'getAccountingData' : ActorMethod<
    [CompanyId],
    { 'invoices' : Array<Invoice>, 'transactions' : Array<Transaction> }
  >,
  'getCRMData' : ActorMethod<
    [CompanyId],
    {
      'logs' : Array<CommunicationLog>,
      'opportunities' : Array<SalesOpportunity>,
      'customers' : Array<Customer>,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompany' : ActorMethod<[string], [] | [Company]>,
  /**
   * / ==========================
   * / Dashboard Summary
   * / ==========================
   */
  'getDashboardSummary' : ActorMethod<[CompanyId], DashboardSummary>,
  'getFinancialSummary' : ActorMethod<[CompanyId], FinancialSummary>,
  'getGrantedModules' : ActorMethod<[CompanyId, Principal], Array<string>>,
  'getHRData' : ActorMethod<
    [CompanyId],
    {
      'employees' : Array<EmployeeRecord>,
      'leaveRequests' : Array<LeaveRequest>,
      'salaries' : Array<SalaryInfo>,
    }
  >,
  'getInventoryData' : ActorMethod<
    [CompanyId],
    { 'movements' : Array<StockMovement>, 'products' : Array<Product> }
  >,
  'getManufacturingData' : ActorMethod<
    [CompanyId],
    { 'workOrders' : Array<WorkOrder>, 'bomItems' : Array<BOMItem> }
  >,
  'getMyEmployeeCode' : ActorMethod<[], [] | [string]>,
  'getProcurementData' : ActorMethod<
    [CompanyId],
    { 'orders' : Array<PurchaseOrder>, 'suppliers' : Array<Supplier> }
  >,
  'getProjectData' : ActorMethod<
    [CompanyId],
    { 'tasks' : Array<ProjectTask>, 'projects' : Array<Project> }
  >,
  'getStaffForCompany' : ActorMethod<[CompanyId], Array<Staff>>,
  'getStaffName' : ActorMethod<[Principal], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkflowData' : ActorMethod<
    [CompanyId],
    { 'tasks' : Array<WorkflowTask> }
  >,
  'grantModuleAccess' : ActorMethod<[CompanyId, Principal, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmployeeInCompany' : ActorMethod<[string], boolean>,
  'isRegisteredAsCompany' : ActorMethod<[], [] | [string]>,
  'listDefaultRoles' : ActorMethod<[], Array<Role>>,
  'listRolesForCompany' : ActorMethod<[string], Array<Role>>,
  'removeBOMItem' : ActorMethod<[CompanyId, string], boolean>,
  'removeCustomRole' : ActorMethod<[string, string], undefined>,
  'removeCustomer' : ActorMethod<[CompanyId, string], boolean>,
  'removeEmployee' : ActorMethod<[CompanyId, string], boolean>,
  'removeProduct' : ActorMethod<[CompanyId, string], boolean>,
  'removeProject' : ActorMethod<[CompanyId, string], boolean>,
  'removeProjectTask' : ActorMethod<[CompanyId, string], boolean>,
  'removePurchaseOrder' : ActorMethod<[CompanyId, string], boolean>,
  'removeStaffFromCompany' : ActorMethod<[CompanyId, Principal], boolean>,
  'removeSupplier' : ActorMethod<[CompanyId, string], boolean>,
  'removeTransaction' : ActorMethod<[CompanyId, string], boolean>,
  'removeWorkOrder' : ActorMethod<[CompanyId, string], boolean>,
  'removeWorkflowTask' : ActorMethod<[CompanyId, string], boolean>,
  'revokeModuleAccess' : ActorMethod<[CompanyId, Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBOMItem' : ActorMethod<[CompanyId, BOMItem], BOMItem>,
  'updateCompany' : ActorMethod<[CompanyId, CompanyProfile], Company>,
  'updateCustomer' : ActorMethod<[CompanyId, Customer], Customer>,
  'updateEmployee' : ActorMethod<[CompanyId, EmployeeRecord], EmployeeRecord>,
  'updateInvoice' : ActorMethod<[CompanyId, Invoice], Invoice>,
  'updateLeaveRequest' : ActorMethod<[CompanyId, LeaveRequest], LeaveRequest>,
  'updateProduct' : ActorMethod<[CompanyId, Product], Product>,
  'updateProject' : ActorMethod<[CompanyId, Project], Project>,
  'updateProjectTask' : ActorMethod<[CompanyId, ProjectTask], ProjectTask>,
  'updatePurchaseOrder' : ActorMethod<
    [CompanyId, PurchaseOrder],
    PurchaseOrder
  >,
  'updateSalesOpportunity' : ActorMethod<
    [CompanyId, SalesOpportunity],
    SalesOpportunity
  >,
  'updateStaffRole' : ActorMethod<
    [CompanyId, Principal, string],
    RoleAssignmentResult
  >,
  'updateSupplier' : ActorMethod<[CompanyId, Supplier], Supplier>,
  'updateTransaction' : ActorMethod<[CompanyId, Transaction], Transaction>,
  'updateWorkOrder' : ActorMethod<[CompanyId, WorkOrder], WorkOrder>,
  'updateWorkflowTask' : ActorMethod<[CompanyId, WorkflowTask], WorkflowTask>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];