/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CompanyId = IDL.Text;
export const CommunicationLog = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'logType' : IDL.Text,
  'customerId' : IDL.Text,
  'companyId' : CompanyId,
});
export const Role = IDL.Record({
  'permissions' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'parentRole' : IDL.Opt(IDL.Text),
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'contactInfo' : IDL.Text,
  'customerCompanyName' : IDL.Text,
  'name' : IDL.Text,
  'companyId' : CompanyId,
});
export const EmployeeRecord = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'principal' : IDL.Opt(IDL.Principal),
  'hireDate' : IDL.Text,
  'name' : IDL.Text,
  'department' : IDL.Text,
  'companyId' : CompanyId,
});
export const InvoiceLineItem = IDL.Record({
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'lineItems' : IDL.Vec(InvoiceLineItem),
  'client' : IDL.Text,
  'total' : IDL.Nat,
  'date' : IDL.Text,
  'companyId' : CompanyId,
});
export const LeaveRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'endDate' : IDL.Text,
  'employeeId' : IDL.Text,
  'leaveType' : IDL.Text,
  'startDate' : IDL.Text,
  'companyId' : CompanyId,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'quantityOnHand' : IDL.Nat,
  'category' : IDL.Text,
  'unitPrice' : IDL.Nat,
  'companyId' : CompanyId,
});
export const SalaryInfo = IDL.Record({
  'id' : IDL.Text,
  'employeeId' : IDL.Text,
  'currency' : IDL.Text,
  'baseSalary' : IDL.Nat,
  'companyId' : CompanyId,
});
export const SalesOpportunity = IDL.Record({
  'id' : IDL.Text,
  'closeDate' : IDL.Text,
  'stage' : IDL.Text,
  'estimatedValue' : IDL.Nat,
  'customerId' : IDL.Text,
  'companyId' : CompanyId,
});
export const EmployeeCode = IDL.Text;
export const RoleAssignmentResult = IDL.Variant({
  'alreadyAssigned' : IDL.Null,
  'invalidCode' : IDL.Null,
  'invalidRole' : IDL.Null,
  'success' : IDL.Null,
  'insufficientPermissions' : IDL.Null,
});
export const StockMovement = IDL.Record({
  'id' : IDL.Text,
  'date' : IDL.Text,
  'productId' : IDL.Text,
  'movementType' : IDL.Text,
  'quantity' : IDL.Nat,
  'reason' : IDL.Text,
  'companyId' : CompanyId,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'transactionType' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Nat,
  'companyId' : CompanyId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PhoneNumber = IDL.Record({
  'countryCode' : IDL.Text,
  'number' : IDL.Text,
});
export const CompanyProfile = IDL.Record({
  'employeeCount' : IDL.Nat,
  'name' : IDL.Text,
  'sector' : IDL.Text,
  'email' : IDL.Text,
  'foundingYear' : IDL.Nat,
  'taxNumber' : IDL.Text,
  'address' : IDL.Text,
  'authorizedPerson' : IDL.Text,
  'phone' : PhoneNumber,
});
export const Company = IDL.Record({
  'id' : CompanyId,
  'employeeCount' : IDL.Nat,
  'managers' : IDL.Vec(IDL.Principal),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'sector' : IDL.Text,
  'email' : IDL.Text,
  'foundingYear' : IDL.Nat,
  'taxNumber' : IDL.Text,
  'address' : IDL.Text,
  'authorizedPerson' : IDL.Text,
  'phone' : PhoneNumber,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'deadline' : IDL.Text,
  'teamMembers' : IDL.Vec(IDL.Principal),
  'companyId' : CompanyId,
});
export const ProjectTask = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'assignee' : IDL.Opt(IDL.Principal),
  'title' : IDL.Text,
  'dueDate' : IDL.Text,
  'projectId' : IDL.Text,
  'companyId' : CompanyId,
});
export const CompanyMembership = IDL.Record({
  'roleCode' : IDL.Nat,
  'grantedModules' : IDL.Vec(IDL.Text),
  'companyId' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'roleCode' : IDL.Nat,
  'employeeCode' : IDL.Text,
  'name' : IDL.Text,
  'projectManager' : IDL.Text,
  'memberships' : IDL.Vec(CompanyMembership),
  'companyId' : IDL.Text,
});
export const DashboardSummary = IDL.Record({
  'totalEmployees' : IDL.Nat,
  'openProjects' : IDL.Nat,
  'pendingInvoices' : IDL.Nat,
  'totalStaff' : IDL.Nat,
  'lowStockProducts' : IDL.Nat,
  'totalCustomers' : IDL.Nat,
});
export const FinancialSummary = IDL.Record({
  'invoiceCount' : IDL.Nat,
  'totalIncome' : IDL.Nat,
  'totalExpenses' : IDL.Nat,
  'paidInvoiceCount' : IDL.Nat,
  'netBalance' : IDL.Int,
});
export const Staff = IDL.Record({
  'roleCode' : IDL.Nat,
  'principal' : IDL.Principal,
  'employeeCode' : EmployeeCode,
  'grantedModules' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'projectManager' : IDL.Text,
  'memberships' : IDL.Vec(CompanyMembership),
  'companyId' : CompanyId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCommunicationLog' : IDL.Func(
      [CompanyId, CommunicationLog],
      [CommunicationLog],
      [],
    ),
  'addCustomRole' : IDL.Func([IDL.Text, Role], [], []),
  'addCustomer' : IDL.Func([CompanyId, Customer], [Customer], []),
  'addEmployee' : IDL.Func([CompanyId, EmployeeRecord], [EmployeeRecord], []),
  'addInvoice' : IDL.Func([CompanyId, Invoice], [Invoice], []),
  'addLeaveRequest' : IDL.Func([CompanyId, LeaveRequest], [LeaveRequest], []),
  'addProduct' : IDL.Func([CompanyId, Product], [Product], []),
  'addSalaryInfo' : IDL.Func([CompanyId, SalaryInfo], [SalaryInfo], []),
  'addSalesOpportunity' : IDL.Func(
      [CompanyId, SalesOpportunity],
      [SalesOpportunity],
      [],
    ),
  'addStaffToCompany' : IDL.Func(
      [CompanyId, EmployeeCode, IDL.Text],
      [RoleAssignmentResult],
      [],
    ),
  'addStockMovement' : IDL.Func(
      [CompanyId, StockMovement],
      [StockMovement],
      [],
    ),
  'addTransaction' : IDL.Func([CompanyId, Transaction], [Transaction], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCompany' : IDL.Func([CompanyProfile], [Company], []),
  'createProject' : IDL.Func([CompanyId, Project], [Project], []),
  'createProjectTask' : IDL.Func([CompanyId, ProjectTask], [ProjectTask], []),
  'findByName' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'findByOwner' : IDL.Func([IDL.Principal], [IDL.Opt(Company)], ['query']),
  'findByToken' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'getAccountingData' : IDL.Func(
      [CompanyId],
      [
        IDL.Record({
          'invoices' : IDL.Vec(Invoice),
          'transactions' : IDL.Vec(Transaction),
        }),
      ],
      ['query'],
    ),
  'getCRMData' : IDL.Func(
      [CompanyId],
      [
        IDL.Record({
          'logs' : IDL.Vec(CommunicationLog),
          'opportunities' : IDL.Vec(SalesOpportunity),
          'customers' : IDL.Vec(Customer),
        }),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'getDashboardSummary' : IDL.Func([CompanyId], [DashboardSummary], ['query']),
  'getFinancialSummary' : IDL.Func([CompanyId], [FinancialSummary], ['query']),
  'getGrantedModules' : IDL.Func(
      [CompanyId, IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getHRData' : IDL.Func(
      [CompanyId],
      [
        IDL.Record({
          'employees' : IDL.Vec(EmployeeRecord),
          'leaveRequests' : IDL.Vec(LeaveRequest),
          'salaries' : IDL.Vec(SalaryInfo),
        }),
      ],
      ['query'],
    ),
  'getInventoryData' : IDL.Func(
      [CompanyId],
      [
        IDL.Record({
          'movements' : IDL.Vec(StockMovement),
          'products' : IDL.Vec(Product),
        }),
      ],
      ['query'],
    ),
  'getMyEmployeeCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getProjectData' : IDL.Func(
      [CompanyId],
      [
        IDL.Record({
          'tasks' : IDL.Vec(ProjectTask),
          'projects' : IDL.Vec(Project),
        }),
      ],
      ['query'],
    ),
  'getStaffForCompany' : IDL.Func([CompanyId], [IDL.Vec(Staff)], ['query']),
  'getStaffName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantModuleAccess' : IDL.Func([CompanyId, IDL.Principal, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmployeeInCompany' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isRegisteredAsCompany' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'listDefaultRoles' : IDL.Func([], [IDL.Vec(Role)], ['query']),
  'listRolesForCompany' : IDL.Func([IDL.Text], [IDL.Vec(Role)], ['query']),
  'removeCustomRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeCustomer' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
  'removeEmployee' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
  'removeProduct' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
  'removeProject' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
  'removeProjectTask' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
  'removeStaffFromCompany' : IDL.Func(
      [CompanyId, IDL.Principal],
      [IDL.Bool],
      [],
    ),
  'removeTransaction' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
  'revokeModuleAccess' : IDL.Func([CompanyId, IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCompany' : IDL.Func([CompanyId, CompanyProfile], [Company], []),
  'updateCustomer' : IDL.Func([CompanyId, Customer], [Customer], []),
  'updateEmployee' : IDL.Func(
      [CompanyId, EmployeeRecord],
      [EmployeeRecord],
      [],
    ),
  'updateInvoice' : IDL.Func([CompanyId, Invoice], [Invoice], []),
  'updateLeaveRequest' : IDL.Func(
      [CompanyId, LeaveRequest],
      [LeaveRequest],
      [],
    ),
  'updateProduct' : IDL.Func([CompanyId, Product], [Product], []),
  'updateProject' : IDL.Func([CompanyId, Project], [Project], []),
  'updateProjectTask' : IDL.Func([CompanyId, ProjectTask], [ProjectTask], []),
  'updateSalesOpportunity' : IDL.Func(
      [CompanyId, SalesOpportunity],
      [SalesOpportunity],
      [],
    ),
  'updateStaffRole' : IDL.Func(
      [CompanyId, IDL.Principal, IDL.Text],
      [RoleAssignmentResult],
      [],
    ),
  'updateTransaction' : IDL.Func([CompanyId, Transaction], [Transaction], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CompanyId = IDL.Text;
  const CommunicationLog = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'logType' : IDL.Text,
    'customerId' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Role = IDL.Record({
    'permissions' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'parentRole' : IDL.Opt(IDL.Text),
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'contactInfo' : IDL.Text,
    'customerCompanyName' : IDL.Text,
    'name' : IDL.Text,
    'companyId' : CompanyId,
  });
  const EmployeeRecord = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'principal' : IDL.Opt(IDL.Principal),
    'hireDate' : IDL.Text,
    'name' : IDL.Text,
    'department' : IDL.Text,
    'companyId' : CompanyId,
  });
  const InvoiceLineItem = IDL.Record({
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'lineItems' : IDL.Vec(InvoiceLineItem),
    'client' : IDL.Text,
    'total' : IDL.Nat,
    'date' : IDL.Text,
    'companyId' : CompanyId,
  });
  const LeaveRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'endDate' : IDL.Text,
    'employeeId' : IDL.Text,
    'leaveType' : IDL.Text,
    'startDate' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'quantityOnHand' : IDL.Nat,
    'category' : IDL.Text,
    'unitPrice' : IDL.Nat,
    'companyId' : CompanyId,
  });
  const SalaryInfo = IDL.Record({
    'id' : IDL.Text,
    'employeeId' : IDL.Text,
    'currency' : IDL.Text,
    'baseSalary' : IDL.Nat,
    'companyId' : CompanyId,
  });
  const SalesOpportunity = IDL.Record({
    'id' : IDL.Text,
    'closeDate' : IDL.Text,
    'stage' : IDL.Text,
    'estimatedValue' : IDL.Nat,
    'customerId' : IDL.Text,
    'companyId' : CompanyId,
  });
  const EmployeeCode = IDL.Text;
  const RoleAssignmentResult = IDL.Variant({
    'alreadyAssigned' : IDL.Null,
    'invalidCode' : IDL.Null,
    'invalidRole' : IDL.Null,
    'success' : IDL.Null,
    'insufficientPermissions' : IDL.Null,
  });
  const StockMovement = IDL.Record({
    'id' : IDL.Text,
    'date' : IDL.Text,
    'productId' : IDL.Text,
    'movementType' : IDL.Text,
    'quantity' : IDL.Nat,
    'reason' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'transactionType' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Nat,
    'companyId' : CompanyId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PhoneNumber = IDL.Record({
    'countryCode' : IDL.Text,
    'number' : IDL.Text,
  });
  const CompanyProfile = IDL.Record({
    'employeeCount' : IDL.Nat,
    'name' : IDL.Text,
    'sector' : IDL.Text,
    'email' : IDL.Text,
    'foundingYear' : IDL.Nat,
    'taxNumber' : IDL.Text,
    'address' : IDL.Text,
    'authorizedPerson' : IDL.Text,
    'phone' : PhoneNumber,
  });
  const Company = IDL.Record({
    'id' : CompanyId,
    'employeeCount' : IDL.Nat,
    'managers' : IDL.Vec(IDL.Principal),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'sector' : IDL.Text,
    'email' : IDL.Text,
    'foundingYear' : IDL.Nat,
    'taxNumber' : IDL.Text,
    'address' : IDL.Text,
    'authorizedPerson' : IDL.Text,
    'phone' : PhoneNumber,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'deadline' : IDL.Text,
    'teamMembers' : IDL.Vec(IDL.Principal),
    'companyId' : CompanyId,
  });
  const ProjectTask = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'assignee' : IDL.Opt(IDL.Principal),
    'title' : IDL.Text,
    'dueDate' : IDL.Text,
    'projectId' : IDL.Text,
    'companyId' : CompanyId,
  });
  const CompanyMembership = IDL.Record({
    'roleCode' : IDL.Nat,
    'grantedModules' : IDL.Vec(IDL.Text),
    'companyId' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'roleCode' : IDL.Nat,
    'employeeCode' : IDL.Text,
    'name' : IDL.Text,
    'projectManager' : IDL.Text,
    'memberships' : IDL.Vec(CompanyMembership),
    'companyId' : IDL.Text,
  });
  const DashboardSummary = IDL.Record({
    'totalEmployees' : IDL.Nat,
    'openProjects' : IDL.Nat,
    'pendingInvoices' : IDL.Nat,
    'totalStaff' : IDL.Nat,
    'lowStockProducts' : IDL.Nat,
    'totalCustomers' : IDL.Nat,
  });
  const FinancialSummary = IDL.Record({
    'invoiceCount' : IDL.Nat,
    'totalIncome' : IDL.Nat,
    'totalExpenses' : IDL.Nat,
    'paidInvoiceCount' : IDL.Nat,
    'netBalance' : IDL.Int,
  });
  const Staff = IDL.Record({
    'roleCode' : IDL.Nat,
    'principal' : IDL.Principal,
    'employeeCode' : EmployeeCode,
    'grantedModules' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'projectManager' : IDL.Text,
    'memberships' : IDL.Vec(CompanyMembership),
    'companyId' : CompanyId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCommunicationLog' : IDL.Func(
        [CompanyId, CommunicationLog],
        [CommunicationLog],
        [],
      ),
    'addCustomRole' : IDL.Func([IDL.Text, Role], [], []),
    'addCustomer' : IDL.Func([CompanyId, Customer], [Customer], []),
    'addEmployee' : IDL.Func([CompanyId, EmployeeRecord], [EmployeeRecord], []),
    'addInvoice' : IDL.Func([CompanyId, Invoice], [Invoice], []),
    'addLeaveRequest' : IDL.Func([CompanyId, LeaveRequest], [LeaveRequest], []),
    'addProduct' : IDL.Func([CompanyId, Product], [Product], []),
    'addSalaryInfo' : IDL.Func([CompanyId, SalaryInfo], [SalaryInfo], []),
    'addSalesOpportunity' : IDL.Func(
        [CompanyId, SalesOpportunity],
        [SalesOpportunity],
        [],
      ),
    'addStaffToCompany' : IDL.Func(
        [CompanyId, EmployeeCode, IDL.Text],
        [RoleAssignmentResult],
        [],
      ),
    'addStockMovement' : IDL.Func(
        [CompanyId, StockMovement],
        [StockMovement],
        [],
      ),
    'addTransaction' : IDL.Func([CompanyId, Transaction], [Transaction], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCompany' : IDL.Func([CompanyProfile], [Company], []),
    'createProject' : IDL.Func([CompanyId, Project], [Project], []),
    'createProjectTask' : IDL.Func([CompanyId, ProjectTask], [ProjectTask], []),
    'findByName' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'findByOwner' : IDL.Func([IDL.Principal], [IDL.Opt(Company)], ['query']),
    'findByToken' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'getAccountingData' : IDL.Func(
        [CompanyId],
        [
          IDL.Record({
            'invoices' : IDL.Vec(Invoice),
            'transactions' : IDL.Vec(Transaction),
          }),
        ],
        ['query'],
      ),
    'getCRMData' : IDL.Func(
        [CompanyId],
        [
          IDL.Record({
            'logs' : IDL.Vec(CommunicationLog),
            'opportunities' : IDL.Vec(SalesOpportunity),
            'customers' : IDL.Vec(Customer),
          }),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'getDashboardSummary' : IDL.Func(
        [CompanyId],
        [DashboardSummary],
        ['query'],
      ),
    'getFinancialSummary' : IDL.Func(
        [CompanyId],
        [FinancialSummary],
        ['query'],
      ),
    'getGrantedModules' : IDL.Func(
        [CompanyId, IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getHRData' : IDL.Func(
        [CompanyId],
        [
          IDL.Record({
            'employees' : IDL.Vec(EmployeeRecord),
            'leaveRequests' : IDL.Vec(LeaveRequest),
            'salaries' : IDL.Vec(SalaryInfo),
          }),
        ],
        ['query'],
      ),
    'getInventoryData' : IDL.Func(
        [CompanyId],
        [
          IDL.Record({
            'movements' : IDL.Vec(StockMovement),
            'products' : IDL.Vec(Product),
          }),
        ],
        ['query'],
      ),
    'getMyEmployeeCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getProjectData' : IDL.Func(
        [CompanyId],
        [
          IDL.Record({
            'tasks' : IDL.Vec(ProjectTask),
            'projects' : IDL.Vec(Project),
          }),
        ],
        ['query'],
      ),
    'getStaffForCompany' : IDL.Func([CompanyId], [IDL.Vec(Staff)], ['query']),
    'getStaffName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantModuleAccess' : IDL.Func(
        [CompanyId, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmployeeInCompany' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isRegisteredAsCompany' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'listDefaultRoles' : IDL.Func([], [IDL.Vec(Role)], ['query']),
    'listRolesForCompany' : IDL.Func([IDL.Text], [IDL.Vec(Role)], ['query']),
    'removeCustomRole' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeCustomer' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
    'removeEmployee' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
    'removeProduct' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
    'removeProject' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
    'removeProjectTask' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
    'removeStaffFromCompany' : IDL.Func(
        [CompanyId, IDL.Principal],
        [IDL.Bool],
        [],
      ),
    'removeTransaction' : IDL.Func([CompanyId, IDL.Text], [IDL.Bool], []),
    'revokeModuleAccess' : IDL.Func(
        [CompanyId, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCompany' : IDL.Func([CompanyId, CompanyProfile], [Company], []),
    'updateCustomer' : IDL.Func([CompanyId, Customer], [Customer], []),
    'updateEmployee' : IDL.Func(
        [CompanyId, EmployeeRecord],
        [EmployeeRecord],
        [],
      ),
    'updateInvoice' : IDL.Func([CompanyId, Invoice], [Invoice], []),
    'updateLeaveRequest' : IDL.Func(
        [CompanyId, LeaveRequest],
        [LeaveRequest],
        [],
      ),
    'updateProduct' : IDL.Func([CompanyId, Product], [Product], []),
    'updateProject' : IDL.Func([CompanyId, Project], [Project], []),
    'updateProjectTask' : IDL.Func([CompanyId, ProjectTask], [ProjectTask], []),
    'updateSalesOpportunity' : IDL.Func(
        [CompanyId, SalesOpportunity],
        [SalesOpportunity],
        [],
      ),
    'updateStaffRole' : IDL.Func(
        [CompanyId, IDL.Principal, IDL.Text],
        [RoleAssignmentResult],
        [],
      ),
    'updateTransaction' : IDL.Func([CompanyId, Transaction], [Transaction], []),
  });
};

export const init = ({ IDL }) => { return []; };