/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Company {
  'id' : CompanyId,
  'employeeCount' : bigint,
  'managers' : Array<Principal>,
  'owner' : Principal,
  'name' : string,
  'sector' : string,
  'email' : string,
  'foundingYear' : bigint,
  'taxNumber' : string,
  'address' : string,
  'authorizedPerson' : string,
  'phone' : PhoneNumber,
}
export type CompanyId = string;
export interface CompanyProfile {
  'employeeCount' : bigint,
  'name' : string,
  'sector' : string,
  'email' : string,
  'foundingYear' : bigint,
  'taxNumber' : string,
  'address' : string,
  'authorizedPerson' : string,
  'phone' : PhoneNumber,
}
export type EmployeeCode = string;
export interface PhoneNumber { 'countryCode' : string, 'number' : string }
export interface Role {
  'permissions' : Array<string>,
  'name' : string,
  'parentRole' : [] | [string],
}
export type RoleAssignmentResult = { 'alreadyAssigned' : null } |
  { 'invalidCode' : null } |
  { 'invalidRole' : null } |
  { 'success' : null } |
  { 'insufficientPermissions' : null };
export interface Staff {
  'roleCode' : bigint,
  'principal' : Principal,
  'employeeCode' : EmployeeCode,
  'name' : string,
  'projectManager' : string,
  'companyId' : CompanyId,
}
export interface UserProfile {
  'roleCode' : bigint,
  'employeeCode' : string,
  'name' : string,
  'projectManager' : string,
  'companyId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStaffToCompany' : ActorMethod<
    [CompanyId, EmployeeCode, string],
    RoleAssignmentResult
  >,
  'adminAssignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'adminListAllCompanies' : ActorMethod<[], Array<Company>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCompany' : ActorMethod<[CompanyProfile], Company>,
  'findByName' : ActorMethod<[string], [] | [Company]>,
  'findByOwner' : ActorMethod<[Principal], [] | [Company]>,
  'findByToken' : ActorMethod<[string], [] | [Company]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompany' : ActorMethod<[string], [] | [Company]>,
  'getMyEmployeeCode' : ActorMethod<[], [] | [string]>,
  'getStaffForCompany' : ActorMethod<[CompanyId], Array<Staff>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isEmployeeInCompany' : ActorMethod<[string], boolean>,
  'isRegisteredAsCompany' : ActorMethod<[], [] | [string]>,
  'listDefaultRoles' : ActorMethod<[], Array<Role>>,
  'listRolesForCompany' : ActorMethod<[string], Array<Role>>,
  'removeStaffFromCompany' : ActorMethod<[CompanyId, Principal], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCompany' : ActorMethod<[CompanyId, CompanyProfile], Company>,
  'updateRole' : ActorMethod<[string, Role], undefined>,
  'updateStaffRole' : ActorMethod<
    [CompanyId, Principal, string],
    RoleAssignmentResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];