/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CompanyId = IDL.Text;
export const EmployeeCode = IDL.Text;
export const RoleAssignmentResult = IDL.Variant({
  'alreadyAssigned' : IDL.Null,
  'invalidCode' : IDL.Null,
  'invalidRole' : IDL.Null,
  'success' : IDL.Null,
  'insufficientPermissions' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PhoneNumber = IDL.Record({
  'countryCode' : IDL.Text,
  'number' : IDL.Text,
});
export const Company = IDL.Record({
  'id' : CompanyId,
  'employeeCount' : IDL.Nat,
  'managers' : IDL.Vec(IDL.Principal),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'sector' : IDL.Text,
  'email' : IDL.Text,
  'foundingYear' : IDL.Nat,
  'taxNumber' : IDL.Text,
  'address' : IDL.Text,
  'authorizedPerson' : IDL.Text,
  'phone' : PhoneNumber,
});
export const CompanyProfile = IDL.Record({
  'employeeCount' : IDL.Nat,
  'name' : IDL.Text,
  'sector' : IDL.Text,
  'email' : IDL.Text,
  'foundingYear' : IDL.Nat,
  'taxNumber' : IDL.Text,
  'address' : IDL.Text,
  'authorizedPerson' : IDL.Text,
  'phone' : PhoneNumber,
});
export const UserProfile = IDL.Record({
  'roleCode' : IDL.Nat,
  'employeeCode' : IDL.Text,
  'name' : IDL.Text,
  'projectManager' : IDL.Text,
  'companyId' : IDL.Text,
});
export const Staff = IDL.Record({
  'roleCode' : IDL.Nat,
  'principal' : IDL.Principal,
  'employeeCode' : EmployeeCode,
  'name' : IDL.Text,
  'projectManager' : IDL.Text,
  'companyId' : CompanyId,
});
export const Role = IDL.Record({
  'permissions' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'parentRole' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStaffToCompany' : IDL.Func(
      [CompanyId, EmployeeCode, IDL.Text],
      [RoleAssignmentResult],
      [],
    ),
  'adminAssignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'adminListAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCompany' : IDL.Func([CompanyProfile], [Company], []),
  'findByName' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'findByOwner' : IDL.Func([IDL.Principal], [IDL.Opt(Company)], ['query']),
  'findByToken' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
  'getMyEmployeeCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getStaffForCompany' : IDL.Func([CompanyId], [IDL.Vec(Staff)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isEmployeeInCompany' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isRegisteredAsCompany' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'listDefaultRoles' : IDL.Func([], [IDL.Vec(Role)], ['query']),
  'listRolesForCompany' : IDL.Func([IDL.Text], [IDL.Vec(Role)], ['query']),
  'removeStaffFromCompany' : IDL.Func(
      [CompanyId, IDL.Principal],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCompany' : IDL.Func([CompanyId, CompanyProfile], [Company], []),
  'updateRole' : IDL.Func([IDL.Text, Role], [], []),
  'updateStaffRole' : IDL.Func(
      [CompanyId, IDL.Principal, IDL.Text],
      [RoleAssignmentResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CompanyId = IDL.Text;
  const EmployeeCode = IDL.Text;
  const RoleAssignmentResult = IDL.Variant({
    'alreadyAssigned' : IDL.Null,
    'invalidCode' : IDL.Null,
    'invalidRole' : IDL.Null,
    'success' : IDL.Null,
    'insufficientPermissions' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PhoneNumber = IDL.Record({
    'countryCode' : IDL.Text,
    'number' : IDL.Text,
  });
  const Company = IDL.Record({
    'id' : CompanyId,
    'employeeCount' : IDL.Nat,
    'managers' : IDL.Vec(IDL.Principal),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'sector' : IDL.Text,
    'email' : IDL.Text,
    'foundingYear' : IDL.Nat,
    'taxNumber' : IDL.Text,
    'address' : IDL.Text,
    'authorizedPerson' : IDL.Text,
    'phone' : PhoneNumber,
  });
  const CompanyProfile = IDL.Record({
    'employeeCount' : IDL.Nat,
    'name' : IDL.Text,
    'sector' : IDL.Text,
    'email' : IDL.Text,
    'foundingYear' : IDL.Nat,
    'taxNumber' : IDL.Text,
    'address' : IDL.Text,
    'authorizedPerson' : IDL.Text,
    'phone' : PhoneNumber,
  });
  const UserProfile = IDL.Record({
    'roleCode' : IDL.Nat,
    'employeeCode' : IDL.Text,
    'name' : IDL.Text,
    'projectManager' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const Staff = IDL.Record({
    'roleCode' : IDL.Nat,
    'principal' : IDL.Principal,
    'employeeCode' : EmployeeCode,
    'name' : IDL.Text,
    'projectManager' : IDL.Text,
    'companyId' : CompanyId,
  });
  const Role = IDL.Record({
    'permissions' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'parentRole' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStaffToCompany' : IDL.Func(
        [CompanyId, EmployeeCode, IDL.Text],
        [RoleAssignmentResult],
        [],
      ),
    'adminAssignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'adminListAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCompany' : IDL.Func([CompanyProfile], [Company], []),
    'findByName' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'findByOwner' : IDL.Func([IDL.Principal], [IDL.Opt(Company)], ['query']),
    'findByToken' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompany' : IDL.Func([IDL.Text], [IDL.Opt(Company)], ['query']),
    'getMyEmployeeCode' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getStaffForCompany' : IDL.Func([CompanyId], [IDL.Vec(Staff)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isEmployeeInCompany' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isRegisteredAsCompany' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'listDefaultRoles' : IDL.Func([], [IDL.Vec(Role)], ['query']),
    'listRolesForCompany' : IDL.Func([IDL.Text], [IDL.Vec(Role)], ['query']),
    'removeStaffFromCompany' : IDL.Func(
        [CompanyId, IDL.Principal],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCompany' : IDL.Func([CompanyId, CompanyProfile], [Company], []),
    'updateRole' : IDL.Func([IDL.Text, Role], [], []),
    'updateStaffRole' : IDL.Func(
        [CompanyId, IDL.Principal, IDL.Text],
        [RoleAssignmentResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };