/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    roleCode: bigint;
    employeeCode: string;
    name: string;
    projectManager: string;
    memberships: Array<CompanyMembership>;
    companyId: string;
}
export interface CommunicationLog {
    id: string;
    date: string;
    note: string;
    logType: string;
    customerId: string;
    companyId: CompanyId;
}
export interface Role {
    permissions: Array<string>;
    name: string;
    parentRole?: string;
}
export interface Transaction {
    id: string;
    transactionType: string;
    date: string;
    description: string;
    category: string;
    amount: bigint;
    companyId: CompanyId;
}
export interface PhoneNumber {
    countryCode: string;
    number: string;
}
export type EmployeeCode = string;
export interface LeaveRequest {
    id: string;
    status: string;
    endDate: string;
    employeeId: string;
    leaveType: string;
    startDate: string;
    companyId: CompanyId;
}
export interface BOMItem {
    id: string;
    unit: string;
    workOrderId: string;
    quantity: bigint;
    materialName: string;
    companyId: CompanyId;
}
export interface Staff {
    roleCode: bigint;
    principal: Principal;
    employeeCode: EmployeeCode;
    grantedModules: Array<string>;
    name: string;
    projectManager: string;
    memberships: Array<CompanyMembership>;
    companyId: CompanyId;
}
export interface EmployeeRecord {
    id: string;
    title: string;
    principal?: Principal;
    hireDate: string;
    name: string;
    department: string;
    companyId: CompanyId;
}
export interface SalesOpportunity {
    id: string;
    closeDate: string;
    stage: string;
    estimatedValue: bigint;
    customerId: string;
    companyId: CompanyId;
}
export interface CompanyMembership {
    roleCode: bigint;
    grantedModules: Array<string>;
    companyId: string;
}
export interface PurchaseOrder {
    id: string;
    status: string;
    orderDate: string;
    totalAmount: bigint;
    expectedDelivery: string;
    items: string;
    supplierId: string;
    companyId: CompanyId;
}
export interface StockMovement {
    id: string;
    date: string;
    productId: string;
    movementType: string;
    quantity: bigint;
    reason: string;
    companyId: CompanyId;
}
export interface FinancialSummary {
    invoiceCount: bigint;
    totalIncome: bigint;
    totalExpenses: bigint;
    paidInvoiceCount: bigint;
    netBalance: bigint;
}
export interface CompanyProfile {
    employeeCount: bigint;
    name: string;
    sector: string;
    email: string;
    foundingYear: bigint;
    taxNumber: string;
    address: string;
    authorizedPerson: string;
    phone: PhoneNumber;
}
export interface WorkflowTask {
    id: string;
    status: string;
    assignee?: Principal;
    title: string;
    tags: Array<string>;
    dueDate: string;
    description: string;
    priority: string;
    companyId: CompanyId;
}
export interface WorkOrder {
    id: string;
    status: string;
    endDate: string;
    productName: string;
    notes: string;
    quantity: bigint;
    startDate: string;
    companyId: CompanyId;
}
export interface ProjectTask {
    id: string;
    status: string;
    assignee?: Principal;
    title: string;
    dueDate: string;
    projectId: string;
    companyId: CompanyId;
}
export interface Invoice {
    id: string;
    status: string;
    lineItems: Array<InvoiceLineItem>;
    client: string;
    total: bigint;
    date: string;
    companyId: CompanyId;
}
export interface DashboardSummary {
    totalEmployees: bigint;
    openProjects: bigint;
    pendingInvoices: bigint;
    totalStaff: bigint;
    lowStockProducts: bigint;
    totalCustomers: bigint;
}
export interface Customer {
    id: string;
    contactInfo: string;
    customerCompanyName: string;
    name: string;
    companyId: CompanyId;
}
export interface Company {
    id: CompanyId;
    employeeCount: bigint;
    managers: Array<Principal>;
    owner: Principal;
    name: string;
    sector: string;
    email: string;
    foundingYear: bigint;
    taxNumber: string;
    address: string;
    authorizedPerson: string;
    phone: PhoneNumber;
}
export type CompanyId = string;
export interface SalaryInfo {
    id: string;
    employeeId: string;
    currency: string;
    baseSalary: bigint;
    companyId: CompanyId;
}
export interface Supplier {
    id: string;
    contactInfo: string;
    name: string;
    category: string;
    rating: bigint;
    companyId: CompanyId;
}
export interface Project {
    id: string;
    status: string;
    name: string;
    description: string;
    deadline: string;
    teamMembers: Array<Principal>;
    companyId: CompanyId;
}
export interface Product {
    id: string;
    sku: string;
    name: string;
    quantityOnHand: bigint;
    category: string;
    unitPrice: bigint;
    companyId: CompanyId;
}
export interface InvoiceLineItem {
    description: string;
    quantity: bigint;
    unitPrice: bigint;
}
export enum RoleAssignmentResult {
    alreadyAssigned = "alreadyAssigned",
    invalidCode = "invalidCode",
    invalidRole = "invalidRole",
    success = "success",
    insufficientPermissions = "insufficientPermissions"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBOMItem(companyId: CompanyId, bomItem: BOMItem): Promise<BOMItem>;
    addCommunicationLog(companyId: CompanyId, log: CommunicationLog): Promise<CommunicationLog>;
    addCustomRole(companyId: string, role: Role): Promise<void>;
    /**
     * / ==========================
     * / CRM Module
     * / ==========================
     */
    addCustomer(companyId: CompanyId, customer: Customer): Promise<Customer>;
    /**
     * / ==========================
     * / HR Module
     * / ==========================
     */
    addEmployee(companyId: CompanyId, employee: EmployeeRecord): Promise<EmployeeRecord>;
    addInvoice(companyId: CompanyId, invoice: Invoice): Promise<Invoice>;
    addLeaveRequest(companyId: CompanyId, request: LeaveRequest): Promise<LeaveRequest>;
    /**
     * / ==========================
     * / Inventory Module
     * / ==========================
     */
    addProduct(companyId: CompanyId, product: Product): Promise<Product>;
    addPurchaseOrder(companyId: CompanyId, order: PurchaseOrder): Promise<PurchaseOrder>;
    addSalaryInfo(companyId: CompanyId, salary: SalaryInfo): Promise<SalaryInfo>;
    addSalesOpportunity(companyId: CompanyId, opportunity: SalesOpportunity): Promise<SalesOpportunity>;
    addStaffToCompany(companyId: CompanyId, employeeCode: EmployeeCode, roleName: string): Promise<RoleAssignmentResult>;
    addStockMovement(companyId: CompanyId, movement: StockMovement): Promise<StockMovement>;
    /**
     * / ==========================
     * / Procurement Module
     * / ==========================
     */
    addSupplier(companyId: CompanyId, supplier: Supplier): Promise<Supplier>;
    /**
     * / ==========================
     * / Accounting Module
     * / ==========================
     */
    addTransaction(companyId: CompanyId, tx: Transaction): Promise<Transaction>;
    /**
     * / ==========================
     * / Manufacturing Module
     * / ==========================
     */
    addWorkOrder(companyId: CompanyId, workOrder: WorkOrder): Promise<WorkOrder>;
    /**
     * / ==========================
     * / Workflow Module
     * / ==========================
     */
    addWorkflowTask(companyId: CompanyId, task: WorkflowTask): Promise<WorkflowTask>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCompany(profile: CompanyProfile): Promise<Company>;
    /**
     * / ==========================
     * / Project Management Module
     * / ==========================
     */
    createProject(companyId: CompanyId, project: Project): Promise<Project>;
    createProjectTask(companyId: CompanyId, task: ProjectTask): Promise<ProjectTask>;
    findByName(name: string): Promise<Company | null>;
    findByOwner(owner: Principal): Promise<Company | null>;
    findByToken(token: string): Promise<Company | null>;
    getAccountingData(companyId: CompanyId): Promise<{
        invoices: Array<Invoice>;
        transactions: Array<Transaction>;
    }>;
    getCRMData(companyId: CompanyId): Promise<{
        logs: Array<CommunicationLog>;
        opportunities: Array<SalesOpportunity>;
        customers: Array<Customer>;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompany(companyId: string): Promise<Company | null>;
    /**
     * / ==========================
     * / Dashboard Summary
     * / ==========================
     */
    getDashboardSummary(companyId: CompanyId): Promise<DashboardSummary>;
    getFinancialSummary(companyId: CompanyId): Promise<FinancialSummary>;
    getGrantedModules(companyId: CompanyId, staffPrincipal: Principal): Promise<Array<string>>;
    getHRData(companyId: CompanyId): Promise<{
        employees: Array<EmployeeRecord>;
        leaveRequests: Array<LeaveRequest>;
        salaries: Array<SalaryInfo>;
    }>;
    getInventoryData(companyId: CompanyId): Promise<{
        movements: Array<StockMovement>;
        products: Array<Product>;
    }>;
    getManufacturingData(companyId: CompanyId): Promise<{
        workOrders: Array<WorkOrder>;
        bomItems: Array<BOMItem>;
    }>;
    getMyEmployeeCode(): Promise<string | null>;
    getProcurementData(companyId: CompanyId): Promise<{
        orders: Array<PurchaseOrder>;
        suppliers: Array<Supplier>;
    }>;
    getProjectData(companyId: CompanyId): Promise<{
        tasks: Array<ProjectTask>;
        projects: Array<Project>;
    }>;
    getStaffForCompany(companyId: CompanyId): Promise<Array<Staff>>;
    getStaffName(principal: Principal): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkflowData(companyId: CompanyId): Promise<{
        tasks: Array<WorkflowTask>;
    }>;
    grantModuleAccess(companyId: CompanyId, staffPrincipal: Principal, moduleName: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isEmployeeInCompany(companyId: string): Promise<boolean>;
    isRegisteredAsCompany(): Promise<string | null>;
    listDefaultRoles(): Promise<Array<Role>>;
    listRolesForCompany(companyId: string): Promise<Array<Role>>;
    removeBOMItem(companyId: CompanyId, bomItemId: string): Promise<boolean>;
    removeCustomRole(companyId: string, roleName: string): Promise<void>;
    removeCustomer(companyId: CompanyId, customerId: string): Promise<boolean>;
    removeEmployee(companyId: CompanyId, employeeId: string): Promise<boolean>;
    removeProduct(companyId: CompanyId, productId: string): Promise<boolean>;
    removeProject(companyId: CompanyId, projectId: string): Promise<boolean>;
    removeProjectTask(companyId: CompanyId, taskId: string): Promise<boolean>;
    removePurchaseOrder(companyId: CompanyId, orderId: string): Promise<boolean>;
    removeStaffFromCompany(companyId: CompanyId, staffPrincipal: Principal): Promise<boolean>;
    removeSupplier(companyId: CompanyId, supplierId: string): Promise<boolean>;
    removeTransaction(companyId: CompanyId, txId: string): Promise<boolean>;
    removeWorkOrder(companyId: CompanyId, workOrderId: string): Promise<boolean>;
    removeWorkflowTask(companyId: CompanyId, taskId: string): Promise<boolean>;
    revokeModuleAccess(companyId: CompanyId, staffPrincipal: Principal, moduleName: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBOMItem(companyId: CompanyId, updatedBOMItem: BOMItem): Promise<BOMItem>;
    updateCompany(id: CompanyId, profile: CompanyProfile): Promise<Company>;
    updateCustomer(companyId: CompanyId, updatedCustomer: Customer): Promise<Customer>;
    updateEmployee(companyId: CompanyId, updatedEmployee: EmployeeRecord): Promise<EmployeeRecord>;
    updateInvoice(companyId: CompanyId, updatedInvoice: Invoice): Promise<Invoice>;
    updateLeaveRequest(companyId: CompanyId, updatedRequest: LeaveRequest): Promise<LeaveRequest>;
    updateProduct(companyId: CompanyId, updatedProduct: Product): Promise<Product>;
    updateProject(companyId: CompanyId, updatedProject: Project): Promise<Project>;
    updateProjectTask(companyId: CompanyId, updatedTask: ProjectTask): Promise<ProjectTask>;
    updatePurchaseOrder(companyId: CompanyId, updatedOrder: PurchaseOrder): Promise<PurchaseOrder>;
    updateSalesOpportunity(companyId: CompanyId, updatedOpportunity: SalesOpportunity): Promise<SalesOpportunity>;
    updateStaffRole(companyId: CompanyId, staffPrincipal: Principal, newRoleName: string): Promise<RoleAssignmentResult>;
    updateSupplier(companyId: CompanyId, updatedSupplier: Supplier): Promise<Supplier>;
    updateTransaction(companyId: CompanyId, updatedTx: Transaction): Promise<Transaction>;
    updateWorkOrder(companyId: CompanyId, updatedWorkOrder: WorkOrder): Promise<WorkOrder>;
    updateWorkflowTask(companyId: CompanyId, updatedTask: WorkflowTask): Promise<WorkflowTask>;
}
import type { Company as _Company, CompanyId as _CompanyId, EmployeeRecord as _EmployeeRecord, LeaveRequest as _LeaveRequest, Project as _Project, ProjectTask as _ProjectTask, Role as _Role, RoleAssignmentResult as _RoleAssignmentResult, SalaryInfo as _SalaryInfo, UserProfile as _UserProfile, UserRole as _UserRole, WorkflowTask as _WorkflowTask } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBOMItem(arg0: CompanyId, arg1: BOMItem): Promise<BOMItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addBOMItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBOMItem(arg0, arg1);
            return result;
        }
    }
    async addCommunicationLog(arg0: CompanyId, arg1: CommunicationLog): Promise<CommunicationLog> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommunicationLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommunicationLog(arg0, arg1);
            return result;
        }
    }
    async addCustomRole(arg0: string, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomRole(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomRole(arg0, to_candid_Role_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addCustomer(arg0: CompanyId, arg1: Customer): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1);
            return result;
        }
    }
    async addEmployee(arg0: CompanyId, arg1: EmployeeRecord): Promise<EmployeeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addEmployee(arg0, to_candid_EmployeeRecord_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_EmployeeRecord_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEmployee(arg0, to_candid_EmployeeRecord_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_EmployeeRecord_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addInvoice(arg0: CompanyId, arg1: Invoice): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvoice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvoice(arg0, arg1);
            return result;
        }
    }
    async addLeaveRequest(arg0: CompanyId, arg1: LeaveRequest): Promise<LeaveRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.addLeaveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLeaveRequest(arg0, arg1);
            return result;
        }
    }
    async addProduct(arg0: CompanyId, arg1: Product): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1);
            return result;
        }
    }
    async addPurchaseOrder(arg0: CompanyId, arg1: PurchaseOrder): Promise<PurchaseOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.addPurchaseOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPurchaseOrder(arg0, arg1);
            return result;
        }
    }
    async addSalaryInfo(arg0: CompanyId, arg1: SalaryInfo): Promise<SalaryInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalaryInfo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalaryInfo(arg0, arg1);
            return result;
        }
    }
    async addSalesOpportunity(arg0: CompanyId, arg1: SalesOpportunity): Promise<SalesOpportunity> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesOpportunity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesOpportunity(arg0, arg1);
            return result;
        }
    }
    async addStaffToCompany(arg0: CompanyId, arg1: EmployeeCode, arg2: string): Promise<RoleAssignmentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.addStaffToCompany(arg0, arg1, arg2);
                return from_candid_RoleAssignmentResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStaffToCompany(arg0, arg1, arg2);
            return from_candid_RoleAssignmentResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async addStockMovement(arg0: CompanyId, arg1: StockMovement): Promise<StockMovement> {
        if (this.processError) {
            try {
                const result = await this.actor.addStockMovement(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStockMovement(arg0, arg1);
            return result;
        }
    }
    async addSupplier(arg0: CompanyId, arg1: Supplier): Promise<Supplier> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplier(arg0, arg1);
            return result;
        }
    }
    async addTransaction(arg0: CompanyId, arg1: Transaction): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(arg0, arg1);
            return result;
        }
    }
    async addWorkOrder(arg0: CompanyId, arg1: WorkOrder): Promise<WorkOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkOrder(arg0, arg1);
            return result;
        }
    }
    async addWorkflowTask(arg0: CompanyId, arg1: WorkflowTask): Promise<WorkflowTask> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkflowTask(arg0, to_candid_WorkflowTask_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_WorkflowTask_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkflowTask(arg0, to_candid_WorkflowTask_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_WorkflowTask_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCompany(arg0: CompanyProfile): Promise<Company> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompany(arg0);
            return result;
        }
    }
    async createProject(arg0: CompanyId, arg1: Project): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.createProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProject(arg0, arg1);
            return result;
        }
    }
    async createProjectTask(arg0: CompanyId, arg1: ProjectTask): Promise<ProjectTask> {
        if (this.processError) {
            try {
                const result = await this.actor.createProjectTask(arg0, to_candid_ProjectTask_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ProjectTask_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProjectTask(arg0, to_candid_ProjectTask_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ProjectTask_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async findByName(arg0: string): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findByName(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findByName(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async findByOwner(arg0: Principal): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findByOwner(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findByOwner(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async findByToken(arg0: string): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.findByToken(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findByToken(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAccountingData(arg0: CompanyId): Promise<{
        invoices: Array<Invoice>;
        transactions: Array<Transaction>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccountingData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccountingData(arg0);
            return result;
        }
    }
    async getCRMData(arg0: CompanyId): Promise<{
        logs: Array<CommunicationLog>;
        opportunities: Array<SalesOpportunity>;
        customers: Array<Customer>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCRMData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCRMData(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompany(arg0: string): Promise<Company | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompany(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompany(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(arg0: CompanyId): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary(arg0);
            return result;
        }
    }
    async getFinancialSummary(arg0: CompanyId): Promise<FinancialSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinancialSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinancialSummary(arg0);
            return result;
        }
    }
    async getGrantedModules(arg0: CompanyId, arg1: Principal): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrantedModules(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrantedModules(arg0, arg1);
            return result;
        }
    }
    async getHRData(arg0: CompanyId): Promise<{
        employees: Array<EmployeeRecord>;
        leaveRequests: Array<LeaveRequest>;
        salaries: Array<SalaryInfo>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHRData(arg0);
                return from_candid_record_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHRData(arg0);
            return from_candid_record_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInventoryData(arg0: CompanyId): Promise<{
        movements: Array<StockMovement>;
        products: Array<Product>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventoryData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventoryData(arg0);
            return result;
        }
    }
    async getManufacturingData(arg0: CompanyId): Promise<{
        workOrders: Array<WorkOrder>;
        bomItems: Array<BOMItem>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getManufacturingData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getManufacturingData(arg0);
            return result;
        }
    }
    async getMyEmployeeCode(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmployeeCode();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmployeeCode();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProcurementData(arg0: CompanyId): Promise<{
        orders: Array<PurchaseOrder>;
        suppliers: Array<Supplier>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProcurementData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProcurementData(arg0);
            return result;
        }
    }
    async getProjectData(arg0: CompanyId): Promise<{
        tasks: Array<ProjectTask>;
        projects: Array<Project>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectData(arg0);
                return from_candid_record_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectData(arg0);
            return from_candid_record_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStaffForCompany(arg0: CompanyId): Promise<Array<Staff>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffForCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffForCompany(arg0);
            return result;
        }
    }
    async getStaffName(arg0: Principal): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaffName(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaffName(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkflowData(arg0: CompanyId): Promise<{
        tasks: Array<WorkflowTask>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkflowData(arg0);
                return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkflowData(arg0);
            return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantModuleAccess(arg0: CompanyId, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantModuleAccess(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantModuleAccess(arg0, arg1, arg2);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isEmployeeInCompany(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isEmployeeInCompany(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isEmployeeInCompany(arg0);
            return result;
        }
    }
    async isRegisteredAsCompany(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegisteredAsCompany();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegisteredAsCompany();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listDefaultRoles(): Promise<Array<Role>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDefaultRoles();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDefaultRoles();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRolesForCompany(arg0: string): Promise<Array<Role>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRolesForCompany(arg0);
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRolesForCompany(arg0);
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeBOMItem(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBOMItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBOMItem(arg0, arg1);
            return result;
        }
    }
    async removeCustomRole(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCustomRole(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCustomRole(arg0, arg1);
            return result;
        }
    }
    async removeCustomer(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCustomer(arg0, arg1);
            return result;
        }
    }
    async removeEmployee(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEmployee(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEmployee(arg0, arg1);
            return result;
        }
    }
    async removeProduct(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProduct(arg0, arg1);
            return result;
        }
    }
    async removeProject(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProject(arg0, arg1);
            return result;
        }
    }
    async removeProjectTask(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProjectTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProjectTask(arg0, arg1);
            return result;
        }
    }
    async removePurchaseOrder(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removePurchaseOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePurchaseOrder(arg0, arg1);
            return result;
        }
    }
    async removeStaffFromCompany(arg0: CompanyId, arg1: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeStaffFromCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeStaffFromCompany(arg0, arg1);
            return result;
        }
    }
    async removeSupplier(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeSupplier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeSupplier(arg0, arg1);
            return result;
        }
    }
    async removeTransaction(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTransaction(arg0, arg1);
            return result;
        }
    }
    async removeWorkOrder(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorkOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorkOrder(arg0, arg1);
            return result;
        }
    }
    async removeWorkflowTask(arg0: CompanyId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeWorkflowTask(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeWorkflowTask(arg0, arg1);
            return result;
        }
    }
    async revokeModuleAccess(arg0: CompanyId, arg1: Principal, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeModuleAccess(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeModuleAccess(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBOMItem(arg0: CompanyId, arg1: BOMItem): Promise<BOMItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBOMItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBOMItem(arg0, arg1);
            return result;
        }
    }
    async updateCompany(arg0: CompanyId, arg1: CompanyProfile): Promise<Company> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompany(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompany(arg0, arg1);
            return result;
        }
    }
    async updateCustomer(arg0: CompanyId, arg1: Customer): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return result;
        }
    }
    async updateEmployee(arg0: CompanyId, arg1: EmployeeRecord): Promise<EmployeeRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeRecord_n3(this._uploadFile, this._downloadFile, arg1));
                return from_candid_EmployeeRecord_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_EmployeeRecord_n3(this._uploadFile, this._downloadFile, arg1));
            return from_candid_EmployeeRecord_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateInvoice(arg0: CompanyId, arg1: Invoice): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoice(arg0, arg1);
            return result;
        }
    }
    async updateLeaveRequest(arg0: CompanyId, arg1: LeaveRequest): Promise<LeaveRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeaveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeaveRequest(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: CompanyId, arg1: Product): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1);
            return result;
        }
    }
    async updateProject(arg0: CompanyId, arg1: Project): Promise<Project> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1);
            return result;
        }
    }
    async updateProjectTask(arg0: CompanyId, arg1: ProjectTask): Promise<ProjectTask> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectTask(arg0, to_candid_ProjectTask_n16(this._uploadFile, this._downloadFile, arg1));
                return from_candid_ProjectTask_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectTask(arg0, to_candid_ProjectTask_n16(this._uploadFile, this._downloadFile, arg1));
            return from_candid_ProjectTask_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePurchaseOrder(arg0: CompanyId, arg1: PurchaseOrder): Promise<PurchaseOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePurchaseOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePurchaseOrder(arg0, arg1);
            return result;
        }
    }
    async updateSalesOpportunity(arg0: CompanyId, arg1: SalesOpportunity): Promise<SalesOpportunity> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalesOpportunity(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalesOpportunity(arg0, arg1);
            return result;
        }
    }
    async updateStaffRole(arg0: CompanyId, arg1: Principal, arg2: string): Promise<RoleAssignmentResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStaffRole(arg0, arg1, arg2);
                return from_candid_RoleAssignmentResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStaffRole(arg0, arg1, arg2);
            return from_candid_RoleAssignmentResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSupplier(arg0: CompanyId, arg1: Supplier): Promise<Supplier> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, arg1);
            return result;
        }
    }
    async updateTransaction(arg0: CompanyId, arg1: Transaction): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, arg1);
            return result;
        }
    }
    async updateWorkOrder(arg0: CompanyId, arg1: WorkOrder): Promise<WorkOrder> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkOrder(arg0, arg1);
            return result;
        }
    }
    async updateWorkflowTask(arg0: CompanyId, arg1: WorkflowTask): Promise<WorkflowTask> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkflowTask(arg0, to_candid_WorkflowTask_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_WorkflowTask_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkflowTask(arg0, to_candid_WorkflowTask_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_WorkflowTask_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EmployeeRecord_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeRecord): EmployeeRecord {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectTask_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectTask): ProjectTask {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RoleAssignmentResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleAssignmentResult): RoleAssignmentResult {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_WorkflowTask_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkflowTask): WorkflowTask {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Company]): Company | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    assignee: [] | [Principal];
    title: string;
    tags: Array<string>;
    dueDate: string;
    description: string;
    priority: string;
    companyId: _CompanyId;
}): {
    id: string;
    status: string;
    assignee?: Principal;
    title: string;
    tags: Array<string>;
    dueDate: string;
    description: string;
    priority: string;
    companyId: CompanyId;
} {
    return {
        id: value.id,
        status: value.status,
        assignee: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignee)),
        title: value.title,
        tags: value.tags,
        dueDate: value.dueDate,
        description: value.description,
        priority: value.priority,
        companyId: value.companyId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    assignee: [] | [Principal];
    title: string;
    dueDate: string;
    projectId: string;
    companyId: _CompanyId;
}): {
    id: string;
    status: string;
    assignee?: Principal;
    title: string;
    dueDate: string;
    projectId: string;
    companyId: CompanyId;
} {
    return {
        id: value.id,
        status: value.status,
        assignee: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignee)),
        title: value.title,
        dueDate: value.dueDate,
        projectId: value.projectId,
        companyId: value.companyId
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    employees: Array<_EmployeeRecord>;
    leaveRequests: Array<_LeaveRequest>;
    salaries: Array<_SalaryInfo>;
}): {
    employees: Array<EmployeeRecord>;
    leaveRequests: Array<LeaveRequest>;
    salaries: Array<SalaryInfo>;
} {
    return {
        employees: from_candid_vec_n25(_uploadFile, _downloadFile, value.employees),
        leaveRequests: value.leaveRequests,
        salaries: value.salaries
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_ProjectTask>;
    projects: Array<_Project>;
}): {
    tasks: Array<ProjectTask>;
    projects: Array<Project>;
} {
    return {
        tasks: from_candid_vec_n28(_uploadFile, _downloadFile, value.tasks),
        projects: value.projects
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tasks: Array<_WorkflowTask>;
}): {
    tasks: Array<WorkflowTask>;
} {
    return {
        tasks: from_candid_vec_n30(_uploadFile, _downloadFile, value.tasks)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: Array<string>;
    name: string;
    parentRole: [] | [string];
}): {
    permissions: Array<string>;
    name: string;
    parentRole?: string;
} {
    return {
        permissions: value.permissions,
        name: value.name,
        parentRole: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.parentRole))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    principal: [] | [Principal];
    hireDate: string;
    name: string;
    department: string;
    companyId: _CompanyId;
}): {
    id: string;
    title: string;
    principal?: Principal;
    hireDate: string;
    name: string;
    department: string;
    companyId: CompanyId;
} {
    return {
        id: value.id,
        title: value.title,
        principal: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.principal)),
        hireDate: value.hireDate,
        name: value.name,
        department: value.department,
        companyId: value.companyId
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alreadyAssigned: null;
} | {
    invalidCode: null;
} | {
    invalidRole: null;
} | {
    success: null;
} | {
    insufficientPermissions: null;
}): RoleAssignmentResult {
    return "alreadyAssigned" in value ? RoleAssignmentResult.alreadyAssigned : "invalidCode" in value ? RoleAssignmentResult.invalidCode : "invalidRole" in value ? RoleAssignmentResult.invalidRole : "success" in value ? RoleAssignmentResult.success : "insufficientPermissions" in value ? RoleAssignmentResult.insufficientPermissions : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmployeeRecord>): Array<EmployeeRecord> {
    return value.map((x)=>from_candid_EmployeeRecord_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectTask>): Array<ProjectTask> {
    return value.map((x)=>from_candid_ProjectTask_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkflowTask>): Array<WorkflowTask> {
    return value.map((x)=>from_candid_WorkflowTask_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Role>): Array<Role> {
    return value.map((x)=>from_candid_Role_n32(_uploadFile, _downloadFile, x));
}
function to_candid_EmployeeRecord_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeRecord): _EmployeeRecord {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectTask_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectTask): _ProjectTask {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_WorkflowTask_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkflowTask): _WorkflowTask {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    assignee?: Principal;
    title: string;
    tags: Array<string>;
    dueDate: string;
    description: string;
    priority: string;
    companyId: CompanyId;
}): {
    id: string;
    status: string;
    assignee: [] | [Principal];
    title: string;
    tags: Array<string>;
    dueDate: string;
    description: string;
    priority: string;
    companyId: _CompanyId;
} {
    return {
        id: value.id,
        status: value.status,
        assignee: value.assignee ? candid_some(value.assignee) : candid_none(),
        title: value.title,
        tags: value.tags,
        dueDate: value.dueDate,
        description: value.description,
        priority: value.priority,
        companyId: value.companyId
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    assignee?: Principal;
    title: string;
    dueDate: string;
    projectId: string;
    companyId: CompanyId;
}): {
    id: string;
    status: string;
    assignee: [] | [Principal];
    title: string;
    dueDate: string;
    projectId: string;
    companyId: _CompanyId;
} {
    return {
        id: value.id,
        status: value.status,
        assignee: value.assignee ? candid_some(value.assignee) : candid_none(),
        title: value.title,
        dueDate: value.dueDate,
        projectId: value.projectId,
        companyId: value.companyId
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: Array<string>;
    name: string;
    parentRole?: string;
}): {
    permissions: Array<string>;
    name: string;
    parentRole: [] | [string];
} {
    return {
        permissions: value.permissions,
        name: value.name,
        parentRole: value.parentRole ? candid_some(value.parentRole) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    principal?: Principal;
    hireDate: string;
    name: string;
    department: string;
    companyId: CompanyId;
}): {
    id: string;
    title: string;
    principal: [] | [Principal];
    hireDate: string;
    name: string;
    department: string;
    companyId: _CompanyId;
} {
    return {
        id: value.id,
        title: value.title,
        principal: value.principal ? candid_some(value.principal) : candid_none(),
        hireDate: value.hireDate,
        name: value.name,
        department: value.department,
        companyId: value.companyId
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
